name = "cf-workers-telegram-bot-v2"
main = "packages/worker/src/worker.ts"

workers_dev = true
compatibility_date = "2024-11-11"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "b0aeda8d-2228-4702-bd0a-0d5c43b88775"

# [[r2_buckets]]
# binding = "R2"
# bucket_name = "share"
